apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postservice
  template:
    metadata:
      labels:
        app: postservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: postservice
          image: ghcr.io/jeevanmgts/postservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: Admin@123
            - name: USER_SERVICE_URL
              value: http://userservice:8080
