apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: userservice
          image: ghcr.io/jeevanmgts/userservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: Admin@123
