name: Build & Publish Platform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # REQUIRED for publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: moback4um-github   # MUST match pom.xml
          settings-path: ${{ github.workspace }}

      - name: Build & Deploy to GitHub Packages
        run: mvn clean deploy -DskipTests